# Generated by Django 5.1.7 on 2025-06-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
